config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol, last_price: looked_up_stock.previous_close)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    @stock = Stock.new_from_lookup(params[:stock])

    #render json: @stock
    render 'users/my_portfolio'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FinanceTracker</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<h3>Search for Stocks</h3>
<div id="stock-lookup">
  <%= form_tag search_stocks_path, method: :get, id: "stock-lookup-form" do %>

  <div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, 
          class: "form-control search-box input-lg" %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
        <i class="fa fa-search"></i>Look up a stock
      <% end %>
    </div>
  </div>

  <% end %>
</div>

<div class="well results-block">
    <strong>Symbol:</strong><%= @stock.ticker %>
    <strong>Name: </strong><%= @stock.name %>
    <strong>Price: </strong><%= @stock.last_price %>
  
</div>

app/views/welcome/index.html.erb
<h1> Welcome to finance tracking app </h1>

<%= link_to "logout", destroy_user_session_path, method: :delete %>